version: '3'

services:
  nextjs-app:
    container_name: nextjs_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    volumes:
      - .:/app
      - /app/node_modules

